# Generated by Django 4.0 on 2021-12-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Слаг'),
        ),
    ]
